# Generated by Django 4.2.4 on 2023-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('firmware_file', models.FileField(upload_to='firmwares/')),
            ],
        ),
    ]
