# Generated by Django 4.2.4 on 2023-08-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_devicemodel_rename_device_name_firmware_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='firmware',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.firmwarebranch'),
            preserve_default=False,
        ),
    ]
