# Generated by Django 4.2.4 on 2023-08-13 00:16

from django.db import migrations, models
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_firmwarebranch_device'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('branch', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='firmwarebranch',
            unique_together={('device', 'name')},
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='firmware_file',
        ),
        migrations.AddField(
            model_name='firmware',
            name='Firmware_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=myapp.models.firmware_upload_path),
            preserve_default=False,
        ),
    ]
