# Generated by Django 4.2.4 on 2023-08-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_firmware_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='Firmware_file',
            new_name='firmware_file',
        ),
    ]
