# Generated by Django 4.2.4 on 2023-08-13 00:33

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_firmware_file_firmware_firmware_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='firmware_file',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.firmware_upload_path),
        ),
    ]
