name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  

  delete-old-images:
    #needs: modify-manifest
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ env.IMAGE_NAME }}*
          cut-off: 10 minutes ago UTC-6
          keep-at-least: 2
          account-type: personal
          token: ${{ secrets.cross_repo }}
          timestamp-to-use: created_at